version: "3.8"

services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password
      - POSTGRES_DB=mindConnect_Db
    ports:
      - '5432:5432'
    networks:
      - mindConnect

  backend:
    container_name: mind-connect
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8020:8020'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/mindConnect_Db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      - database
    networks:
      - mindConnect
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8020/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  mindConnect:
    driver: "bridge"

